# Using Pandas

In [240]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 200)
## to make it possible to display multiple output inside one cell 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

<b>load the data from the vehicles.csv file into pandas data frame

In [241]:
## Your Code here

vehicles_df = pd.read_csv("data/vehicles.csv")

First exploration of the dataset:

- How many observations does it have?
- Look at all the columns: do you understand what they mean?
- Look at the raw data: do you see anything weird?
- Look at the data types: are they the expected ones for the information the column contains?

In [242]:
## Your Code here

vehicles_df.info()
vehicles_df.count()
vehicles_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35952 entries, 0 to 35951
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Make                     35952 non-null  object
 1   Model                    35952 non-null  object
 2   Year                     35952 non-null  int64
 3   Engine Displacement      35952 non-null  float64
 4   Cylinders                35952 non-null  float64
 5   Transmission             35952 non-null  object
 6   Drivetrain               35952 non-null  object
 7   Vehicle Class            35952 non-null  object
 8   Fuel Type                35952 non-null  object
 9   Fuel Barrels/Year        35952 non-null  float64
 10  City MPG                 35952 non-null  int64
 11  Highway MPG              35952 non-null  int64
 12  Combined MPG             35952 non-null  int64
 13  CO2 Emission Grams/Mile  35952 non-null  float64
 14  Fuel Cost/Year           35952 non-null  int64
dtypes: float64(4), int64(5), object(6)
memory usage: 4.1+ MB

Make                       35952
Model                      35952
Year                       35952
Engine Displacement        35952
Cylinders                  35952
Transmission               35952
Drivetrain                 35952
Vehicle Class              35952
Fuel Type                  35952
Fuel Barrels/Year          35952
City MPG                   35952
Highway MPG                35952
Combined MPG               35952
CO2 Emission Grams/Mile    35952
Fuel Cost/Year             35952
dtype: int64

,Year,Engine Displacement,Cylinders,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
count,35952.00000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000
mean,2000.71640,3.338493,5.765076,17.609056,17.646139,23.880646,19.929322,475.316339,1892.598465
std,10.08529,1.359395,1.755268,4.467283,4.769349,5.890876,5.112409,119.060773,506.958627
min,1984.00000,0.600000,2.000000,0.060000,6.000000,9.000000,7.000000,37.000000,600.000000
25%,1991.00000,2.200000,4.000000,14.699423,15.000000,20.000000,16.000000,395.000000,1500.000000
50%,2001.00000,3.000000,6.000000,17.347895,17.000000,24.000000,19.000000,467.736842,1850.000000
75%,2010.00000,4.300000,6.000000,20.600625,20.000000,27.000000,23.000000,555.437500,2200.000000
max,2017.00000,8.400000,16.000000,47.087143,58.000000,61.000000,56.000000,1269.571429,5800.000000

###How many observations does it have?

The dataset has 35952 entries.

###Look at all the columns: do you understand what they mean?

We don´t now what year was used for Fuel Cost/Year 

###Look at the raw data: do you see anything weird?

The Minimum of CO2 Emission Grams/Mile and Fuel Barrels/Year looks too low

###Look at the data types: are they the expected ones for the information the column contains?
I would say so

### Cleaning and wrangling data

- Some car brand names refer to the same brand. Replace all brand names that contain the word "Dutton" for simply "Dutton". If you find similar examples, clean their names too. Use `loc` with boolean indexing.

- Convert CO2 Emissions from Grams/Mile to Grams/Km

- Create a binary column that solely indicates if the transmission of a car is automatic or manual. Use `pandas.Series.str.startswith` and .

- convert MPG columns to km_per_liter

In [243]:
## Some car brand names refer to the same brand. Replace all brand names that contain the word "Dutton" for simply "Dutton". If you find similar examples, clean their names too. Use loc with boolean indexing.

vehicles_df.Make.value_counts()

dutton_names = vehicles_df[vehicles_df["Make"].str.contains("Dutton")==True]
vehicles_df["Make"].replace(["E. P. Dutton, Inc.","Superior Coaches Div E.p. Dutton","S and S Coach Company  E.p. Dutton"],"Dutton", inplace=True)

PAS_names = vehicles_df[vehicles_df["Make"].str.contains("PAS")==True]
vehicles_df["Make"].replace(["PAS Inc - GMC","PAS, Inc"],"PAS Inc", inplace=True)

BMW_names = vehicles_df[vehicles_df["Make"].str.contains("BMW")==True]
vehicles_df["Make"].replace(["BMW Alpina"],"BMW", inplace=True)

Grumman_names = vehicles_df[vehicles_df["Make"].str.contains("Grumman")==True]
vehicles_df["Make"].replace(["Grumman Allied Industries","Grumman Olson"],"Grumman", inplace=True)

Saleen_names = vehicles_df[vehicles_df["Make"].str.contains("Saleen")==True]
vehicles_df["Make"].replace(["Saleen Performance"],"Saleen", inplace=True)

#vehicles_df["Make"].[vehicles_df.loc("Make"),str.contains("Dutton")]="Dutton"

Chevrolet                             3643
Ford                                  2946
Dodge                                 2360
GMC                                   2347
Toyota                                1836
BMW                                   1677
Mercedes-Benz                         1284
Nissan                                1253
Volkswagen                            1047
Mitsubishi                             950
Mazda                                  915
Audi                                   890
Porsche                                862
Honda                                  836
Jeep                                   829
Pontiac                                784
Subaru                                 781
Volvo                                  717
Hyundai                                662
Chrysler                               641
Buick                                  537
Mercury                                532
Suzuki                                 512
Cadillac                               508
Kia                                    493
Plymouth                               456
Saab                                   410
Isuzu                                  409
Lexus                                  397
Oldsmobile                             376
Infiniti                               345
Jaguar                                 343
MINI                                   320
Acura                                  302
Saturn                                 278
Lincoln                                273
Ferrari                                208
Rolls-Royce                            160
Eagle                                  156
Geo                                    144
Land Rover                             142
Aston Martin                           133
Bentley                                116
Maserati                               111
Lamborghini                            104
Scion                                   83
Peugeot                                 74
Daewoo                                  67
Ram                                     57
Roush Performance                       53
Lotus                                   53
Fiat                                    43
Alfa Romeo                              41
J.K. Motors                             36
Renault                                 33
Wallace Environmental                   32
Maybach                                 31
American Motors Corporation             22
smart                                   20
Hummer                                  19
Daihatsu                                17
CX Automotive                           16
Merkur                                  14
Federal Coach                           14
Import Trade Services                   13
McLaren Automotive                      13
Spyker                                  13
Sterling                                12
Bugatti                                  8
Yugo                                     8
Genesis                                  7
Tecstar, LP                              6
Mcevoy Motors                            6
Saleen                                   5
VPG                                      5
Bertone                                  5
Panther Car Company Limited              4
Saleen Performance                       4
AM General                               4
TVR Engineering Ltd                      4
Grumman Olson                            4
Texas Coach Company                      4
Vector                                   4
Autokraft Limited                        4
Morgan                                   3
Evans Automobiles                        3
Dacia                                    3
Dabryan Coach Builders Inc               3
Consulier Industries Inc                 3
BMW Alpina                               3
Bitter Gmbh and Co. Kg                   3
SRT                                      2
Ruf Automobile Gmbh                      2
CCC Engineering                          2
Red Shift Ltd.                           2
Bill Dovell Motor Car Company            2
Quantum Technologies                     2
Pagani                                   2
PAS, Inc                                 2
Laforza Automobile Inc                   2
Mobility Ventures LLC                    2
Pininfarina                              2
PAS Inc - GMC                            2
Import Foreign Auto Sales Inc            1
London Taxi                              1
London Coach Co Inc                      1
Qvale                                    1
Grumman Allied Industries                1
Vixen Motor Company                      1
Volga Associated Automobile              1
ASC Incorporated                         1
Isis Imports Ltd                         1
Aurora Cars Ltd                          1
JBA Motorcars, Inc.                      1
Mahindra                                 1
Superior Coaches Div E.p. Dutton         1
Goldacre                                 1
General Motors                           1
Fisker                                   1
Shelby                                   1
Panos                                    1
Panoz Auto-Development                   1
Excalibur Autos                          1
S and S Coach Company  E.p. Dutton       1
Environmental Rsch and Devp Corp         1
E. P. Dutton, Inc.                       1
Lambda Control Systems                   1
Name: Make, dtype: int64

In [244]:
#Convert CO2 Emissions from Grams/Mile to Grams/Km

vehicles_df["CO2 Emission Grams/Mile"]=vehicles_df["CO2 Emission Grams/Mile"]*(1/1.60934)
vehicles_df.rename(columns={"CO2 Emission Grams/Mile":"CO2 Emission Grams/Km"}, inplace=True)
vehicles_df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Km,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,324.831736,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,424.779962,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,345.133719,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,424.779962,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,345.133719,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,151.614948,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,150.993575,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,151.614948,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,152.857693,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,158.450048,1150

Converting Grams/Mile to Grams/Km

1 Mile = 1.60934 Km

Grams/Mile * Mile/Km -> Grams/Mile * 1 Mile/1.60934Km

$$ \frac{Grams}{Mile} * \frac{Mile}{Km} $$

$$ \frac{Grams}{Mile} * \frac{1 Mile}{1.60934Km}  $$

In [245]:
#Create a binary column that solely indicates if the transmission of a car is automatic or manual. Use pandas.Series.str.startswith


vehicles_df["Transmission_Automatic"]=vehicles_df["Transmission"].str.startswith("A", na=False)
vehicles_df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Km,Fuel Cost/Year,Transmission_Automatic
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,324.831736,1950,True
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,424.779962,2550,True
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,345.133719,2100,True
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,424.779962,2550,True
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,345.133719,2550,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,151.614948,1100,True
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,150.993575,1100,True
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,151.614948,1100,True
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,152.857693,1100,True
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,158.450048,1150,False

In [246]:
# convert MPG columns to km_per_liter

vehicles_df["City MPG"]=vehicles_df["City MPG"]*(1.60934/3.78541)
vehicles_df["Highway MPG"]=vehicles_df["Highway MPG"]*(1.60934/3.78541)
vehicles_df["Combined MPG"]=vehicles_df["Combined MPG"]*(1.60934/3.78541)
vehicles_df.rename(columns={"City MPG":"City Km/Liter","Highway MPG":"Highway Km/Liter","Combined MPG":"Combined Km/Liter"}, inplace=True)

vehicles_df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City Km/Liter,Highway Km/Liter,Combined Km/Liter,CO2 Emission Grams/Km,Fuel Cost/Year,Transmission_Automatic
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,7.652571,7.227428,7.227428,324.831736,1950,True
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,5.526857,5.526857,5.526857,424.779962,2550,True
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,6.802286,7.227428,6.802286,345.133719,2100,True
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,5.526857,5.526857,5.526857,424.779962,2550,True
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,5.952000,8.928000,6.802286,345.133719,2550,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,14.454857,16.155428,15.305143,151.614948,1100,True
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,14.454857,16.155428,15.305143,150.993575,1100,True
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,14.454857,16.155428,15.305143,151.614948,1100,True
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,14.454857,16.580571,15.305143,152.857693,1100,True
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,13.604571,16.580571,14.880000,158.450048,1150,False

convert MPG columns to km_per_liter

MPG = Miles/Gallon -> Km/Liter

1 Mile = 1.60934 Km

1 Gallon = 3.78541 Liters

$$ \frac{Miles}{Gallon} -> \frac{Miles}{Gallon} * \frac{Km}{Miles} * \frac{Gallon}{Liters}$$

$$ \frac{Miles}{Gallon} -> \frac{Miles}{Gallon} * \frac{1.60934Km}{ 1Miles} * \frac{1 Gallon}{3.78541 Liters}$$

* ( 1.60934 / 3.78541 )

### Gathering insights:

- How many car makers are there? How many models? Which car maker has the most cars in the dataset?

- When were these cars made? How big is the engine of these cars?

- What's the frequency of different transmissions, drivetrains and fuel types?

- What's the car that consumes the least/most fuel?

In [247]:
## How many car makers are there? How many models? Which car maker has the most cars in the dataset?

print(vehicles_df["Make"].nunique())
#127 car makers

print(vehicles_df["Model"].nunique())
#3608 models

print(vehicles_df.Make.value_counts())
#Chevrolet has the most cars



##When were these cars made? How big is the engine of these cars?

print(vehicles_df["Year"].max(),vehicles_df["Year"].min())
#There were made between 1984 and 2017.

print(vehicles_df["Engine Displacement"].max(),vehicles_df["Engine Displacement"].min())
#Between 0.6  and 8.4 



##What's the frequency of different transmissions, drivetrains and fuel types?
print(vehicles_df.Transmission_Automatic.value_counts())
print(vehicles_df.Drivetrain.value_counts())
print(vehicles_df["Fuel Type"].value_counts())

121
3608
Chevrolet                           3643
Ford                                2946
Dodge                               2360
GMC                                 2347
Toyota                              1836
BMW                                 1680
Mercedes-Benz                       1284
Nissan                              1253
Volkswagen                          1047
Mitsubishi                           950
Mazda                                915
Audi                                 890
Porsche                              862
Honda                                836
Jeep                                 829
Pontiac                              784
Subaru                               781
Volvo                                717
Hyundai                              662
Chrysler                             641
Buick                                537
Mercury                              532
Suzuki                               512
Cadillac                             508
Kia                                  493
Plymouth                             456
Saab                                 410
Isuzu                                409
Lexus                                397
Oldsmobile                           376
Infiniti                             345
Jaguar                               343
MINI                                 320
Acura                                302
Saturn                               278
Lincoln                              273
Ferrari                              208
Rolls-Royce                          160
Eagle                                156
Geo                                  144
Land Rover                           142
Aston Martin                         133
Bentley                              116
Maserati                             111
Lamborghini                          104
Scion                                 83
Peugeot                               74
Daewoo                                67
Ram                                   57
Roush Performance                     53
Lotus                                 53
Fiat                                  43
Alfa Romeo                            41
J.K. Motors                           36
Renault                               33
Wallace Environmental                 32
Maybach                               31
American Motors Corporation           22
smart                                 20
Hummer                                19
Daihatsu                              17
CX Automotive                         16
Federal Coach                         14
Merkur                                14
McLaren Automotive                    13
Spyker                                13
Import Trade Services                 13
Sterling                              12
Saleen                                 9
Yugo                                   8
Bugatti                                8
Genesis                                7
Mcevoy Motors                          6
Tecstar, LP                            6
Grumman                                5
VPG                                    5
Bertone                                5
Panther Car Company Limited            4
PAS Inc                                4
AM General                             4
TVR Engineering Ltd                    4
Texas Coach Company                    4
Vector                                 4
Autokraft Limited                      4
Bitter Gmbh and Co. Kg                 3
Dacia                                  3
Evans Automobiles                      3
Consulier Industries Inc               3
Dutton                                 3
Dabryan Coach Builders Inc             3
Morgan                                 3
CCC Engineering                        2
Bill Dovell Motor Car Company          2
SRT                                    2
Ruf Automobile Gmbh                    2
Quantum Technologies                   2
Red Shift Ltd.                         2
Pininfarina                            2
Laforza Automobile Inc                 2
Pagani                                 2
Mobility Ventures LLC                  2
Excalibur Autos                        1
Panoz Auto-Development                 1
ASC Incorporated                       1
Aurora Cars Ltd                        1
London Coach Co Inc                    1
London Taxi                            1
Volga Associated Automobile            1
Vixen Motor Company                    1
JBA Motorcars, Inc.                    1
Isis Imports Ltd                       1
Mahindra                               1
Import Foreign Auto Sales Inc          1
Goldacre                               1
Qvale                                  1
General Motors                         1
Fisker                                 1
Environmental Rsch and Devp Corp       1
Panos                                  1
Shelby                                 1
Lambda Control Systems                 1
Name: Make, dtype: int64
2017 1984
8.4 0.6
True     24290
False    11662
Name: Transmission_Automatic, dtype: int64
Front-Wheel Drive             13044
Rear-Wheel Drive              12726
4-Wheel or All-Wheel Drive     6503
All-Wheel Drive                2039
4-Wheel Drive                  1058
2-Wheel Drive                   423
Part-time 4-Wheel Drive         158
2-Wheel Drive, Front              1
Name: Drivetrain, dtype: int64
Regular                        23587
Premium                         9921
Gasoline or E85                 1195
Diesel                           911
Premium or E85                   121
Midgrade                          74
CNG                               60
Premium and Electricity           20
Gasoline or natural gas           20
Premium Gas or Electricity        17
Regular Gas and Electricity       16
Gasoline or propane                8
Regular Gas or Electricity         2
Name: Fuel Type, dtype: int64

In [248]:
##What's the car that consumes the least/most fuel?

vehicles_df.loc[vehicles_df["Fuel Barrels/Year"] == vehicles_df["Fuel Barrels/Year"].max()]
#Lamborghini Countach cosumes the most 

vehicles_df.loc[vehicles_df["Fuel Barrels/Year"] == vehicles_df["Fuel Barrels/Year"].min()]
#Honda Civic cosumes the least

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City Km/Liter,Highway Km/Liter,Combined Km/Liter,CO2 Emission Grams/Km,Fuel Cost/Year,Transmission_Automatic
20894,Lamborghini,Countach,1986,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2.550857,4.251429,2.976,788.877073,5800,False
20895,Lamborghini,Countach,1987,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2.550857,4.251429,2.976,788.877073,5800,False
20896,Lamborghini,Countach,1988,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2.550857,4.251429,2.976,788.877073,5800,False
20897,Lamborghini,Countach,1989,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2.550857,4.251429,2.976,788.877073,5800,False
20898,Lamborghini,Countach,1990,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2.550857,4.251429,2.976,788.877073,5800,False

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City Km/Liter,Highway Km/Liter,Combined Km/Liter,CO2 Emission Grams/Km,Fuel Cost/Year,Transmission_Automatic
17395,Honda,Civic Natural Gas,2012,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.06,11.478857,16.155428,13.179428,142.104437,1000,True
17396,Honda,Civic Natural Gas,2013,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.06,11.478857,16.155428,13.179428,135.459257,1000,True
17397,Honda,Civic Natural Gas,2014,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.06,11.478857,16.155428,13.179428,135.459257,1000,True
17398,Honda,Civic Natural Gas,2015,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.06,11.478857,16.155428,13.179428,135.459257,1000,True

What brand has the worse CO2 Emissions on average?

Hint: use the function `sort_values()`

In [259]:
## your Code here

grouped_vehicles_df = vehicles_df.groupby("Make")
mean_df = grouped_vehicles_df.mean()
mean_df.sort_values(by=["CO2 Emission Grams/Km"])

#Vector has the worse CO2 Emissions on average (651.919248)

,Year,Engine Displacement,Cylinders,Fuel Barrels/Year,City Km/Liter,Highway Km/Liter,Combined Km/Liter,CO2 Emission Grams/Km,Fuel Cost/Year,Transmission_Automatic
Make,,,,,,,,,,
Fisker,2012.000000,2.000000,4.000000,6.359255,8.502857,8.928000,8.502857,105.011992,2000.000000,1.000000
smart,2012.500000,0.980000,3.000000,9.208922,14.157257,16.708114,15.220114,153.498052,1110.000000,0.900000
Fiat,2015.069767,1.446512,4.000000,11.383588,11.211907,14.395535,12.408239,189.311494,1386.046512,0.488372
Daihatsu,1990.352941,1.264706,3.705882,11.504567,11.929008,13.804638,12.604235,192.742404,1173.529412,0.235294
MINI,2012.496875,1.631875,3.981250,11.640990,10.801286,14.163900,12.103286,194.935105,1429.531250,0.475000
Scion,2010.783133,2.042169,4.000000,12.316868,10.521005,13.327972,11.571057,205.920389,1275.301205,0.530120
Geo,1992.840278,1.451389,3.743056,12.501873,10.976952,13.093809,11.815428,209.450825,1277.083333,0.451389
Yugo,1988.375000,1.200000,4.000000,13.206218,9.778286,12.010286,10.628571,221.251107,1350.000000,0.000000
Honda,2001.618421,2.162560,4.376794,13.066686,10.132741,12.952109,11.207294,222.160996,1364.832536,0.570574
Renault,1985.969697,1.727273,4.000000,13.345607,9.791169,12.432208,10.796052,223.586374,1359.090909,0.363636
Saturn,2001.834532,2.329496,4.431655,13.957160,8.872945,12.529480,10.229426,233.832051,1439.028777,0.647482
Hyundai,2006.790030,2.360725,4.664653,14.269686,8.917725,12.166021,10.122510,239.241983,1463.066465,0.654079
Red Shift Ltd.,1987.500000,2.000000,4.000000,14.330870,8.077714,13.179428,9.778286,240.093022,1750.000000,0.000000
Dacia,1988.000000,1.400000,4.000000,14.330870,8.928000,11.904000,9.778286,240.093022,1450.000000,0.000000
Daewoo,2000.388060,1.855224,4.029851,14.381540,8.458439,12.322797,9.810013,240.941937,1457.462687,0.507463
Grumman,1985.200000,1.780000,4.000000,14.580069,11.053714,11.563886,11.223771,242.101035,1400.000000,0.600000
Kia,2009.356998,2.351927,4.543611,14.474057,8.910753,11.869505,10.036131,242.732303,1467.748479,0.695740
Volkswagen,2002.928367,2.236008,4.595033,14.594784,9.024236,12.323052,10.243222,244.038998,1579.417383,0.532951
Suzuki,2001.382812,1.966211,4.308594,14.568941,9.120643,11.301991,9.944357,244.042612,1478.222656,0.500000
Panoz Auto-Development,1995.000000,5.000000,8.000000,14.982273,7.652571,12.754286,9.353143,251.006341,1500.000000,0.000000
Bertone,1987.000000,1.500000,4.000000,14.982273,8.502857,11.053714,9.353143,251.006341,1500.000000,0.000000
Subaru,1999.599232,2.223816,4.130602,14.999905,8.515377,11.077666,9.477800,251.230978,1596.670935,0.530090
Eagle,1993.275641,2.135256,4.256410,15.249072,8.306637,11.097319,9.347692,255.476174,1620.833333,0.557692
Pontiac,1994.997449,2.967730,5.247449,15.372605,8.175866,11.629609,9.422012,257.513762,1615.561224,0.674745
Plymouth,1990.267544,2.382237,4.416667,15.460492,8.335037,10.931579,9.305594,259.018217,1624.561404,0.594298
Mazda,2000.582514,2.394754,4.535519,15.628220,8.341628,10.967292,9.316436,261.798342,1639.344262,0.546448
Acura,2003.493377,2.834768,5.231788,15.673371,8.031258,11.028374,9.143387,262.583000,1852.483444,0.678808
Consulier Industries Inc,1991.000000,2.200000,4.000000,15.695714,7.652571,10.203428,8.928000,262.959024,1600.000000,0.000000
Quantum Technologies,1998.500000,2.200000,4.000000,15.695714,8.077714,10.628571,8.928000,262.959024,1600.000000,1.000000
Qvale,2000.000000,4.600000,8.000000,15.695714,7.227428,11.904000,8.928000,262.959024,1600.000000,0.000000
Mitsubishi,1998.796842,2.455895,4.606316,16.010363,8.130074,10.613356,9.059123,268.105004,1715.157895,0.578947
Buick,1997.832402,3.280447,5.582868,16.117492,7.620903,11.147135,8.877331,269.963993,1656.890130,0.918063
Toyota,2000.408497,2.757244,4.967320,16.153677,8.439178,10.608657,9.268160,270.791631,1657.788671,0.651416
Volvo,2002.182706,2.504742,4.945607,16.186996,7.644863,10.655847,8.760196,270.796572,1812.273361,0.746165
Pininfarina,1985.000000,2.000000,4.000000,16.165084,8.077714,9.990857,8.715428,270.822632,1625.000000,0.500000
Mercury,1996.507519,3.022368,5.500000,16.206884,7.938664,10.858724,8.987935,271.489475,1643.045113,0.761278
Panther Car Company Limited,1987.000000,2.300000,4.000000,16.284304,7.971428,9.778286,8.609143,272.819988,1637.500000,0.500000
Oldsmobile,1991.340426,3.176862,5.537234,16.351145,7.530456,10.946298,8.740304,273.849170,1673.005319,0.837766
Lexus,2007.725441,3.615869,6.554156,16.471887,8.084140,10.439024,8.920504,275.240120,1943.450882,0.947103
Saab,2000.541463,2.311220,4.404878,16.448540,7.417187,10.714637,8.593070,275.571531,1774.634146,0.519512
Isis Imports Ltd,1992.000000,3.900000,8.000000,16.480500,6.802286,11.904000,8.502857,276.106976,2000.000000,0.000000
Lotus,2003.867925,2.713208,5.245283,16.507078,7.435989,10.813067,8.631202,276.195577,1993.396226,0.150943
Chrysler,2000.079563,3.065367,5.326053,16.574449,7.456913,10.537706,8.553927,277.609760,1759.828393,0.826833
Audi,2005.260674,2.874607,5.813483,16.725128,7.467706,10.696881,8.641387,280.087391,1997.696629,0.696629
Mcevoy Motors,1987.333333,2.300000,4.000000,16.769632,7.652571,9.636571,8.361143,280.950958,1683.333333,1.000000
Nissan,2001.569034,3.001038,5.273743,16.914320,7.829347,10.258734,8.740367,283.443767,1784.876297,0.596967
BMW,2006.733929,3.237976,6.427976,16.989778,7.321567,10.697151,8.513486,284.384482,2042.440476,0.658333
Infiniti,2008.388406,3.724058,6.289855,17.149036,7.390092,10.187409,8.404273,286.982449,2032.898551,0.881159
London Taxi,2003.000000,2.400000,4.000000,17.372045,8.928000,10.203428,9.353143,287.526112,1650.000000,1.000000
Porsche,2007.577726,3.600232,6.122970,17.199845,7.153448,10.301576,8.293738,288.199235,2112.529002,0.542923
Alfa Romeo,1991.878049,2.556098,5.317073,17.208234,7.268906,10.161951,8.295470,288.287195,1962.195122,0.341463
Genesis,2017.000000,4.171429,6.857143,17.037485,6.923755,10.385633,8.259918,288.405717,1985.714286,1.000000
Volga Associated Automobile,1986.000000,1.600000,4.000000,17.347895,7.652571,9.353143,8.077714,290.638922,1750.000000,0.000000
Evans Automobiles,1990.000000,5.700000,8.000000,17.347895,7.227428,10.203428,8.077714,290.638922,1750.000000,0.000000
Import Foreign Auto Sales Inc,1984.000000,1.000000,4.000000,17.347895,7.652571,8.502857,8.077714,290.638922,1750.000000,0.000000
Peugeot,1988.351351,2.166216,4.162162,17.424751,7.485961,9.381869,8.215598,291.565042,1873.648649,0.540541
Ram,2014.736842,4.191228,6.631579,17.792707,7.063338,10.091549,8.182135,298.360841,1859.649123,1.000000
Lincoln,2006.736264,3.874725,6.593407,18.059533,7.028094,9.905984,8.077714,302.572997,1920.329670,0.989011
McLaren Automotive,2015.153846,3.800000,8.000000,16.932750,6.704176,9.320439,7.685275,303.981385,2250.000000,1.000000
Sterling,1988.833333,2.633333,6.000000,18.160487,6.908571,8.998857,7.723428,304.252727,1833.333333,0.500000
Isuzu,1994.457213,2.753790,4.858191,18.228050,7.367757,9.257512,8.066280,305.229090,1838.264059,0.437653
Merkur,1987.428571,2.471429,4.571429,18.228248,6.923755,9.079837,7.713306,305.387965,1835.714286,0.500000
Jaguar,2006.239067,4.010496,7.434402,18.278121,6.683295,9.820428,7.832296,306.582116,2230.029155,0.932945
General Motors,1989.000000,5.000000,8.000000,18.311667,6.377143,9.353143,7.652571,306.785528,1850.000000,1.000000
Goldacre,1991.000000,2.500000,6.000000,18.311667,6.802286,9.353143,7.652571,306.785528,2250.000000,0.000000
TVR Engineering Ltd,1985.500000,2.800000,6.000000,18.311667,6.377143,9.353143,7.652571,306.785528,2250.000000,0.500000
Cadillac,2005.755906,4.256693,6.933071,18.415347,6.717759,9.835194,7.812418,308.375552,2003.149606,0.907480
Jeep,2000.506634,3.378770,5.355850,18.504940,7.146400,9.099801,7.873605,309.928716,1881.785283,0.580217
Mercedes-Benz,2005.670561,4.059579,7.019470,18.609137,6.902942,9.639882,7.902889,311.421545,2253.933022,0.934579
American Motors Corporation,1984.590909,3.813636,5.545455,18.758092,6.821610,8.580156,7.517299,314.264744,1893.181818,0.363636
Mahindra,2011.000000,2.200000,4.000000,19.109250,8.077714,8.928000,8.502857,316.278723,1800.000000,1.000000
Chevrolet,1998.274225,4.111502,6.333242,18.997583,6.962867,9.467277,7.868585,318.564940,1942.355202,0.681032
Ford,1998.415479,3.750000,6.101494,18.989729,6.982243,9.327311,7.842919,320.296589,1947.657841,0.688730
Shelby,2008.000000,4.600000,8.000000,19.388824,6.377143,9.353143,7.227428,324.831736,2400.000000,0.000000
Morgan,2002.333333,3.966667,8.000000,19.388824,6.377143,9.353143,7.227428,324.831736,2400.000000,0.000000
Lambda Control Systems,1986.000000,3.000000,6.000000,19.388824,6.802286,8.502857,7.227428,324.831736,1950.000000,1.000000
Bill Dovell Motor Car Company,1985.000000,2.300000,4.000000,19.388824,7.227428,7.652571,7.227428,324.831736,1950.000000,1.000000
Autokraft Limited,1989.500000,4.925000,8.000000,19.994724,5.952000,8.715428,7.014857,334.982728,2250.000000,0.000000
Dabryan Coach Builders Inc,1995.000000,4.966667,8.000000,20.250549,5.952000,8.502857,6.944000,339.268702,2033.333333,1.000000
Mobility Ventures LLC,2014.000000,4.600000,8.000000,11.058538,5.314286,7.227428,5.952000,340.201573,2275.000000,1.000000
CX Automotive,1990.375000,2.781250,5.125000,20.491935,6.084857,8.423143,6.882000,343.312774,2500.000000,0.562500
Dodge,1995.776695,3.933983,6.233051,20.507157,6.492436,8.732002,7.310475,344.554180,2125.148305,0.672881
ASC Incorporated,1987.000000,3.800000,6.000000,20.600625,5.952000,8.928000,6.802286,345.133719,2550.000000,1.000000
London Coach Co Inc,1986.000000,2.300000,4.000000,20.600625,6.802286,7.227428,6.802286,345.133719,2100.000000,1.000000
Environmental Rsch and Devp Corp,1989.000000,2.900000,6.000000,20.600625,6.377143,7.227428,6.802286,345.133719,2550.000000,1.000000
Bitter Gmbh and Co. Kg,1986.666667,3.600000,6.000000,21.058417,5.952000,8.077714,6.660571,352.803358,2433.333333,0.333333
VPG,2011.800000,4.600000,8.000000,13.241631,5.186743,7.312457,6.037028,355.006336,2260.000000,1.000000
GMC,1997.533021,4.711632,6.875160,21.178804,6.126803,8.116660,6.852281,355.109034,2143.949723,0.708564
Import Trade Services,1991.230769,2.469231,5.076923,21.262011,6.246330,7.292835,6.606066,356.214289,2473.076923,0.846154
Federal Coach,1995.000000,5.228571,8.000000,21.523078,5.739428,7.834775,6.528979,360.588086,2175.000000,1.000000
Spyker,2007.000000,4.200000,8.000000,21.576281,5.592264,7.848791,6.507956,361.479419,2230.769231,0.153846
Hummer,2008.631579,4.100000,5.789474,21.808782,5.817744,7.428812,6.444271,365.374644,2210.526316,0.631579
Aurora Cars Ltd,1988.000000,4.900000,8.000000,21.974000,5.101714,8.502857,6.377143,368.142634,2200.000000,0.000000
"JBA Motorcars, Inc.",1988.000000,3.000000,6.000000,21.974000,6.377143,6.802286,6.377143,368.142634,2200.000000,1.000000
CCC Engineering,1987.500000,5.700000,8.000000,21.974000,5.526857,8.502857,6.377143,368.142634,2200.000000,1.000000
Panos,1993.000000,4.900000,8.000000,21.974000,5.526857,8.928000,6.377143,368.142634,2200.000000,0.000000
Land Rover,2006.394366,3.896479,7.211268,22.248607,5.769368,7.895082,6.547799,373.280395,2634.507042,0.950704
SRT,2013.500000,8.400000,10.000000,21.974000,5.101714,8.077714,6.377143,377.173251,2700.000000,0.000000
AM General,1984.500000,3.350000,5.000000,22.674670,6.377143,6.377143,6.270857,379.881345,2287.500000,1.000000
PAS Inc,1992.000000,4.300000,6.000000,22.758786,5.739428,7.121143,6.164571,381.290585,2800.000000,1.000000
Maserati,2002.891892,3.586486,7.027027,23.027769,5.400463,7.844077,6.235428,385.686226,2763.063063,0.765766
Roush Performance,2008.962264,5.090566,8.000000,23.140361,5.422577,7.636528,6.232755,386.441107,2853.773585,0.698113
Saleen,1999.333333,5.233333,8.000000,23.166271,5.101714,7.936000,6.093714,388.117406,2583.333333,0.222222
J.K. Motors,1992.416667,3.361111,6.777778,23.338020,5.491428,7.050286,6.081905,390.994816,2393.055556,0.833333
Excalibur Autos,1987.000000,5.000000,8.000000,23.543571,5.101714,7.227428,5.952000,394.438536,2900.000000,1.000000
Vixen Motor Company,1986.000000,2.400000,6.000000,23.886563,6.377143,6.802286,6.802286,395.348404,2250.000000,0.000000
Wallace Environmental,1991.500000,4.315625,7.812500,24.404196,5.287714,6.802286,5.898857,408.857065,2996.875000,0.718750
Pagani,2015.000000,6.000000,12.000000,25.354615,4.676571,7.227428,5.526857,416.941106,3100.000000,1.000000
Aston Martin,2006.458647,5.324060,10.015038,24.998702,4.922707,7.473564,5.772992,417.946348,3002.255639,0.593985
"Tecstar, LP",2008.000000,5.400000,8.000000,25.354615,4.676571,6.377143,5.526857,424.779962,3100.000000,1.000000
Ruf Automobile Gmbh,1987.500000,3.400000,6.000000,25.354615,4.676571,7.652571,5.526857,424.779962,3100.000000,0.000000
Bentley,2008.405172,6.084483,9.586207,25.427330,4.639921,7.454660,5.633143,426.290692,3135.775862,1.000000
Ferrari,2004.879808,4.748558,9.884615,26.424478,4.660220,6.867692,5.428747,442.812798,3203.846154,0.581731
Maybach,2008.580645,5.677419,12.000000,27.058555,4.333714,6.788571,5.184000,453.327003,3341.935484,1.000000
Texas Coach Company,1986.000000,5.000000,8.000000,27.467500,4.676571,5.952000,5.101714,460.178293,2800.000000,1.000000
Lamborghini,2007.346154,5.675962,11.057692,27.969011,4.333187,6.843165,5.240703,469.001266,3444.230769,0.509615
Rolls-Royce,2000.687500,6.698125,9.725000,28.405710,4.275343,6.496714,5.107028,475.397772,3352.500000,1.000000
Dutton,1984.333333,5.366667,8.000000,28.436941,4.818286,6.093714,5.243428,476.419879,2883.333333,1.000000
Laforza Automobile Inc,1989.500000,4.900000,8.000000,29.964545,4.251429,5.526857,4.676571,502.012683,3050.000000,1.000000
Bugatti,2011.125000,8.000000,16.000000,32.961000,3.401143,6.217714,4.251429,542.497235,4050.000000,1.000000
Vector,1994.500000,5.850000,10.000000,38.912292,3.082286,4.676571,3.613714,651.919248,4775.000000,0.500000

Do cars with automatic transmission consume more fuel than cars with manual transmission on average?

In [261]:
## Your Code is here 

grouped_vehicles_df = vehicles_df.groupby("Transmission_Automatic")
mean_df = grouped_vehicles_df.mean()
print(mean_df)

#No, they consume less

,Year,Engine Displacement,Cylinders,Fuel Barrels/Year,City Km/Liter,Highway Km/Liter,Combined Km/Liter,CO2 Emission Grams/Km,Fuel Cost/Year
Transmission_Automatic,,,,,,,,,
False,1997.489367,2.887318,5.179472,16.704904,7.968348,10.715481,8.984980,279.718227,1785.765735
True,2002.265747,3.555109,6.046233,18.043152,7.278292,9.882480,8.226908,302.853002,1943.890490